### ISSUE TITLE
[Issue] Not reading additional libraries

### ISSUE THREAD

**Issue by geekcroft** [adamgot/python-plexlibrary#14]
Hi there,

Using the example recipes such as the 1001 movies - have my current libraries configured as;

```
# Source library details
source_libraries:
  - name: 'Movies Archived'
    folders:
      - '/home/Plex/ACD/Plex/Films'
  - name: 'Movies'
    folders:
      - '/home/Plex/Movies'
```

However it only reads the first one - Archived - not the additional libraries specified.
