### ISSUE TITLE
Multiple Source Library not working.

### ISSUE THREAD

**Issue by xman0980** [adamgot/python-plexlibrary#38]
I see that there is a closed issue about this from before https://github.com/adamgot/python-plexlibrary/issues/4

Has this been fixed? If so, I need some help with my config please.

```source_libraries:
  - name: 'Movies'
    folders:
      - '/home/xorcist/data/.Automation/plexdrive-fuse/MyMedia/Movies'
      - '/home/xorcist/data/.Automation/plexdrive-fuse/MyMedia/Kid Movies/' ```

It's not picking up movies that I have in Kid Movies. I have tried "Kid Movies" and Kid\ Movies/
Let me know what I should change it to in order to get it working correctly. Thanks!

**Comment by jh888** [comment]
I seem to be having the same problem.  In my case, it's only the second directory for the 'Movies' library that it doesn't pick up (Z:\Video\Movies).  The rest all work fine.

```
# Source library details
source_libraries:
  - name: 'Movies'
    folders:
      - 'G:\Video\Movies'
      - 'Z:\Video\Movies'
  - name: 'Kids Movies'
    folders:
      - 'Z:\Video\Childrens Movies'
  - name: 'Christmas Movies'
    folders:
      - 'Z:\Video\Christmas Movies'
```
